# Generated by Django 2.1.8 on 2019-04-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0069_deprecate_nullablecharfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='device_role',
        ),
        migrations.AddField(
            model_name='device',
            name='device_role',
            field=models.ManyToManyField(related_name='devices', to='dcim.DeviceRole'),
        ),
    ]

