# Generated by Django 2.1.8 on 2019-04-10 15:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0005_change_logging'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='local_context_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]

